# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  prisma-app:
    stdin_open: true
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: prisma-api
    ports:
      - "8080:8080"
    restart: always
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data: